services:

  backend:
    build:
      context: .
      dockerfile: docker/php/Dockerfile

    container_name: colmerzia_backend

    restart: unless-stopped

    working_dir: /var/www/html

    volumes:
      - ./backend:/var/www/html

    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started

    networks:
      - colmerzia


  frontend:
    build:
      context: .
      dockerfile: docker/node/Dockerfile

    container_name: colmerzia_frontend

    restart: unless-stopped

    working_dir: /app

    volumes:
      # Código fuente local
      - ./frontend:/app

      # node_modules administrado por Docker
      - frontend_node_modules:/app/node_modules

    ports:
      - "5173:5173"

    depends_on:
      - backend

    command: npm run dev -- --host

    networks:
      - colmerzia


  nginx:
    image: nginx:1.28-alpine

    container_name: colmerzia_nginx

    restart: unless-stopped

    ports:
      - "8080:80"

    volumes:
      - ./backend:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

    depends_on:
      - backend

    networks:
      - colmerzia


  postgres:
    image: postgres:17

    container_name: colmerzia_postgres

    restart: unless-stopped

    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

    ports:
      - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

    networks:
      - colmerzia


  redis:
    image: redis:7-alpine

    container_name: colmerzia_redis

    restart: unless-stopped

    ports:
      - "6379:6379"

    volumes:
      - redis_data:/data

    networks:
      - colmerzia


  mailpit:
    image: axllent/mailpit:latest

    container_name: colmerzia_mailpit

    restart: unless-stopped

    ports:
      - "1025:1025"
      - "8025:8025"

    networks:
      - colmerzia


volumes:
  postgres_data:
  redis_data:
  frontend_node_modules:


networks:
  colmerzia:
    driver: bridge